# Hierarchical Models

Hierarchical models are so named because the are composed of models within models.

## Fixed Effects

In a simple fixed effects (no pooling) model like an ANOVA the expected value for each group is estimated independently of the value for the other groups in the sense that knowing something about the value for one group tells you nothing about the value(s) for the other group.

This might be represented mathematically as follows

$$ L_{i,j} \sim N(\alpha_j, \sigma') $$

where $L_{i,j}$ is the length of the ith fish in the jth group, $\sim N()$ is the normal distribution, $\alpha_i$ is the average (expected) length for the jth group and $\sigma'$ is the standard deviation of the fish within group variation.

## Random Effects

Random effects (partial pooling) allow the distribution of parameter values as opposed to just the distribution of data to be estimated through a hierarchical structure.
In this way knowing something about the value for one group in an ANOVA would tell you something about the value(s) for the other groups and vice versa.

Expanding our ANOVA to include a random effect of group would produce the following hierarchical (mixed-effects) model

$$ \alpha_j \sim N(\bar\alpha, \sigma) $$

$$ L_{i,j} \sim N(\alpha_j, \sigma) $$

where $\bar\alpha$ is the expected length for a typical group and $\sigma$ is the standard deviation of the among group variation.

## No Effects

A third alternative is the no group effects (no pooling) model 

$$ L_{i,j} \sim N(\alpha, \sigma') $$

$\alpha$ is the expected length for all fish pooled together.

In a sense a random effects models represent a balance (partial pooling) between the equivalent fixed effect model (no pooling) and no effect model (complete pooling) depending on the value of $\sigma$.

## Why Random Effects

Random effects (referred to as varying effects by @mcelreath_statistical_2020) can be used when there are at least three groups (ideally five or more) and it makes sense to think about a distribution of groups although the inclusion of random effects particularly multiple nested random effects can slow model converge.

### Pseudoreplication

Random effects can account for pseudoreplication (including overdispersion).

### Missing Data

Random effects allow us to make inferences about groups with little to no data.

### Variability

Random effects allow us to estimate the among group variation.

### Better Predictions

Random effects improve predictions by tuning the value of $\alpha'$

## Frogs in Tanks

<iframe width="700" height="394"
src="https://www.youtube.com/embed/iwVqiiXYeC4?si=dq3Z9Qjx86wci9KK&amp;start=1314" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
