on:
  push:
    branches: 
     - main 

name: bookdown

jobs:
  bookdown:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on:  macOS-latest
    timeout-minutes: 15
    env:
      GITHUB_PAT: ${{ secrets.PRIVATE_ACTIONS_PAT }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install JAGS macOS
        if: runner.os == 'macOS'
        run: brew install jags
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
          with:
            use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install LaTex
        uses: r-lib/actions/setup-tinytex@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Cache bookdown results
        uses: actions/cache@v3
        with:
          path: _bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-
          
      - name: Build site
        run: |
          R -e 'bookdown::render_book("index.Rmd", quiet = TRUE)'

      - name: Build pdf
        run: |
          R -e 'bookdown::render_book("index.Rmd", output_format = "bookdown::pdf_book")'
          
      - name: Build eBook
        run: |
          R -e 'bookdown::render_book("index.Rmd", output_format = "bookdown::epub_book")'
          
      - name: Install npm
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          npm install netlify-cli -g
          netlify deploy --prod --dir _book

